print("1")
print("2")
print("3")
print("4")
print("5")
print("6")
print("7")
print("8")
print("9")
print("10")

a=1
b='dcds'
print(str(a)+b)
print("hello","world", sep="\n")
print("home","alpin","tarxz",sep="/")

print("root","node","child",sep="->")
print("hello, world")
print("hello,world",end='\n')
print("do you want to",end='...')
print("y/n")
print('"one","two","three"','"four","five","six"','"seven","eight","nine","ten"',sep="\n")
print("1","2","3", end=",")
print("4","5","6", end=",")