print("am ganesh")
print("am 23 years old")
print("i woke up at 6:00 am")
print("i came by bus KA03F2911")
print(2+3)
print("3-2")
print("sun raises in 'east' ")
print("there are 9 of us")
print("$%^&")
print("&*()")
print("please don't be late to class")
