print("am ganesh")
print("am 23 years old")
print("i woke up at 6:00 am")
print("i came by bus KA03F2911")
print("2+3=5")
print("3-2=6")
print("sun raises in 'east' ")
print("there are 9 of us")
print("$%^&")
print("&*()")